import math
import random
#testing out the maths 
num = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
num3 = int(input("Enter a third number: "))
num4 = random.randint(1, 100000)


print("The square root of", num, "is", math.sqrt(num))
print("The square root of", num2, "is", math.sqrt(num2))
print("The square root of", num3, "is", math.sqrt(num3))
print("The square root of", num4, "is", math.sqrt(num4))
print ("The floor of", num, "is", math.floor(num))
print ("The floor of", num2, "is", math.floor(num2))
print ("The floor of", num3, "is", math.floor(num3))
print ("The floor of", num4, "is", math.floor(num4))
print("The sum of", num, "and", num2, "is", num + num2)
print("The sum of", num, "and", num3, "is", num + num3)
print("The sum of", num2, "and", num3, "is", num2 + num3)
print("The sum of", num, ",", num2, "and", num3, "is", num + num2 + num3)
print("The sum of", num, ",", num2, ",", num3, "and", num4, "is", num + num2 + num3 + num4)
print("The product of", num, "and", num2, "is", num * num2)
print("The product of", num, "and", num3, "is", num * num3)
print("The product of", num2, "and", num3, "is", num2 * num3)
print("The product of", num, ",", num2, "and", num3, "is", num * num2 * num3)
print("The product of", num, ",", num2, ",", num3, "and", num4, "is", num * num2 * num3 * num4)
print("The difference between", num, "and", num2, "is", num - num2)
print("The difference between", num, "and", num3, "is", num - num3)
print("The difference between", num2, "and", num3, "is", num2 - num3)
print("The difference between", num, ",", num2, "and", num3, "is", num - num2 - num3)
print("The difference between", num, ",", num2, ",", num3, "and", num4, "is", num - num2 - num3 - num4)
print("The quotient of", num, "and", num2, "is", num / num2)
print("The quotient of", num, "and", num3, "is", num / num3)
print("The quotient of", num2, "and", num3, "is", num2 / num3)
print("The quotient of", num, ",", num2, "and", num3, "is", num / num2 / num3)
print("The quotient of", num, ",", num2, ",", num3, "and", num4, "is", num / num2 / num3 / num4)
print("The modulus of", num, "and", num2, "is", num % num2)
print("The modulus of", num, "and", num3, "is", num % num3)
print("The modulus of", num2, "and", num3, "is", num2 % num3)
print("The modulus of", num, ",", num2, "and", num3, "is", num % num2 % num3)
print("The modulus of", num, ",", num2, ",", num3, "and", num4, "is", num % num2 % num3 % num4)
